### ISSUE TITLE
Oracle Java doesn’t work

### ISSUE THREAD

**Issue by Bombardier-C-Kram** [JJTech0130/MultiMC5#28] opened 2020-06-29 12:11 UTC
System Information
-----------------------------
MultiMC version: 5

Operating System: Raspberry Pi OS 64bit Beta

Summary of the issue or suggestion: Cannot run forge 1.12.2 any version but can run vanilla minecraft
----------------------------------------------

What should happen: Forge will launch
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add forge to a 1.12.2 profile

2. Launch profile

3. It crashes with an error

Suspected cause:
---------------------------
I removed all mods and the error still happens when launching onesix launcher.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
https://paste.ee/p/UBHDm

**Comment by Bombardier-C-Kram** [comment] 2020-06-29 12:53
Forge needed java 8, after i added java 8, i still cant launch it... https://paste.ee/p/mekko

**Comment by JJTech0130** [comment] 2020-07-07 16:43
Did you use *Oracle* Java 8? I ran into a similar issue with XAwt.so and it seems to be bundled with OpenJDK 8 but not Oracle JDK 8.

**Comment by Bombardier-C-Kram** [comment] 2020-07-07 21:45
I did download it on oracles website, i used Linux ARM 64 Hard Float ABI. Im not really sure exactly whats causing the error...

**Comment by JJTech0130** [comment] 2020-07-08 14:40
The problem is on line 137 of your second paste. It said it cannot find `libawt_xawt.so`. This is because it is not bundled with Oracle Java for arm. OpenJDK, which is an open source version of the java JDK *does* bundle this lib so it works.
Get OpenJDK from [here](https://adoptopenjdk.net/).

**Comment by JJTech0130** [comment] 2020-07-09 12:04
Closing as it appears the issue is solved, feel free to reopen if it isn’t.

**Closed as completed by JJTech0130** 2020-07-09 12:04 UTC
Labels: wontfix, known issue
